import { StyleSheet } from "react-native";

export const ProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  header: {
    height: 320,
    position: "relative",
    overflow: "hidden",
  },
  headerGradient: {
    flex: 1,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  profileSection: {
    alignItems: "center",
    zIndex: 2,
  },
  themeToggleContainer: {
    position: "absolute",
    top: 20,
    right: 20,
    zIndex: 3,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
  },
  statusDot: {
    position: "absolute",
    bottom: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: "#ffffff",
  },
  name: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  cardsContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 20,
  },
  infoCard: {
    borderRadius: 20,
    padding: 24,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
  },
  skillCard: {
    borderRadius: 20,
    padding: 24,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  icon: {
    fontSize: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  cardContent: {
    gap: 8,
  },
  infoText: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  skillGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  skillBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  skillText: {
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  floatingElement1: {
    position: "absolute",
    top: 100,
    right: -30,
    width: 80,
    height: 80,
    borderRadius: 40,
    opacity: 0.1,
  },
  floatingElement2: {
    position: "absolute",
    top: 200,
    left: -40,
    width: 60,
    height: 60,
    borderRadius: 30,
    opacity: 0.1,
  },
  floatingElement3: {
    position: "absolute",
    bottom: 100,
    right: -20,
    width: 100,
    height: 100,
    borderRadius: 50,
    opacity: 0.08,
  },
});
